version: '3.4'

services:
  mongo-webapp:
    image: mongo:latest
    restart: always

  mongo-fill:
    image: mongo:latest
    volumes:
      - ./mongo_fill:/mongo_fill
    command:
      /mongo_fill/import.sh
    depends_on:
      - mongo-webapp
    links:
      - mongo-webapp

  server:
    image: securewebdevbackend
    build:
      context: server
      dockerfile: ./Dockerfile
    environment:
      JWT_SECRET: ${JWT}
      MONGO_URI: ${MONGO_URI}
    links:
      - mongo-webapp
    depends_on:
      - mongo-webapp

  client:
    image: client
    restart: always
    build:
      context: client
      dockerfile: ./Dockerfile
    links:
      - server
    depends_on:
      - server


  
  nginx:
    depends_on:
      - server
      - client
    restart: always
    build:
      context: nginx
      dockerfile: ./Dockerfile
    ports:
      - 80:80


  
     